begin;
select plan(15);
select has_table('public','platform_admin_invitations','admin invitations are durable');
select has_function('public','admin_merchant_detail',array['uuid'],'merchant detail RPC exists');
select has_function('public','admin_set_device_status',array['uuid','text','text'],'device status RPC exists');
select has_function('public','admin_create_platform_admin_invitation',array['text','text','text'],'admin invite RPC exists');
select has_function('public','admin_search_audit_events',array['text','text','text','uuid','uuid','timestamptz','timestamptz','bigint','integer'],'audit pagination RPC exists');
select is(has_function_privilege('authenticated','public.complete_platform_admin_invitation(uuid,uuid)','execute'),false,'clients cannot complete invitations');
select is(has_function_privilege('authenticated','public.fail_platform_admin_invitation(uuid,text)','execute'),false,'clients cannot forge invitation failures');
select is(has_function_privilege('service_role','public.complete_platform_admin_invitation(uuid,uuid)','execute'),true,'service role completes invitations');
select is(has_function_privilege('authenticated','public.admin_merchant_detail(uuid)','execute'),true,'admins can request merchant details');
select is(has_function_privilege('authenticated','public.admin_search_audit_events(text,text,text,uuid,uuid,timestamptz,timestamptz,bigint,integer)','execute'),true,'admins can use audit pagination endpoint');
select col_is_pk('public','platform_admin_invitations','id','invitation id is primary key');
select has_column('public','platform_admin_invitations','expires_at','invitation expires');
select has_column('public','platform_admin_invitations','invited_by','inviter is attributable');
select has_column('public','platform_admin_invitations','error_code','delivery failure is recorded');
select has_index('public','platform_admin_invitation_pending_email_idx','duplicate active invitations are prevented');
select * from finish();
rollback;
