begin;
select plan(16);
select has_table('public','merchant_operating_periods','merchant periods are persisted');
select has_table('public','merchant_lifecycle_events','merchant lifecycle audit exists');
select has_column('public','tenants','operational_status','merchant operational status exists');
select has_column('public','tenants','admin_archived','merchant archive state exists');
select has_column('public','tenants','current_period_started_at','current accounting period exists');
select has_function('public','admin_payment_settlement_snapshot',array[]::text[],'separated payment and settlement snapshot exists');
select has_function('public','admin_manage_merchant_lifecycle',array['uuid','text','text'],'merchant lifecycle RPC exists');
select is(has_function_privilege('authenticated','public.admin_payment_settlement_snapshot()','execute'),true,'authenticated admin may call snapshot and is authorized server-side');
select is(has_function_privilege('anon','public.admin_payment_settlement_snapshot()','execute'),false,'anonymous user cannot read payment settlement snapshot');
select is(has_function_privilege('authenticated','public.admin_manage_merchant_lifecycle(uuid,text,text)','execute'),true,'authenticated admin may call lifecycle RPC and is authorized server-side');
select is(has_function_privilege('anon','public.admin_manage_merchant_lifecycle(uuid,text,text)','execute'),false,'anonymous user cannot manage merchant lifecycle');
select col_is_pk('public','merchant_lifecycle_events','id','lifecycle events use append-only identity');
select col_is_fk('public','merchant_lifecycle_events','tenant_id','lifecycle event belongs to merchant');
select col_is_fk('public','merchant_operating_periods','tenant_id','period belongs to merchant');
select has_index('public','merchant_operating_periods','merchant_operating_period_open_idx','only one period can remain open');
select isnt_empty($$select 1 from public.merchant_operating_periods$$,'existing merchants receive an initial period');
select * from finish();
rollback;
