project_id = "niagacore"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "niagacore://auth/callback"
additional_redirect_urls = ["niagacore://auth/callback", "niagacore://auth/reset"]
enable_signup = true

[functions.health]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.nia-evaluator]
verify_jwt = false

[functions.notification-dispatch]
verify_jwt = false
