import React from "react";
import {Pressable,StyleSheet,View} from "react-native";
import {supabase} from "@/lib/supabase";
import {useAuth,type ActiveWorkspace,type BusinessOption} from "@/providers/auth-provider";
import {Badge,Button,Card,Field,Header,Row,Screen,Sheet} from "@/ui/components";
import {LocalizedText as Text,localizedAlert} from "@/ui/localized-text";
import {colors} from "@/ui/theme";

const moduleOptions=[{id:"retail",label:"Retail"},{id:"food_service",label:"F&B"},{id:"services",label:"Jasa"},{id:"wholesale",label:"Grosir"}];
export function BusinessManagementScreen({workspace,onBack}:{workspace:ActiveWorkspace;onBack:()=>void}){
  const auth=useAuth();
  const [editing,setEditing]=React.useState<BusinessOption|null|undefined>(undefined),[name,setName]=React.useState(""),[modules,setModules]=React.useState<string[]>(["retail"]),[branchName,setBranchName]=React.useState("Cabang Utama"),[branchCode,setBranchCode]=React.useState("UTAMA"),[busy,setBusy]=React.useState(false),[branchOpen,setBranchOpen]=React.useState(false);
  const openCreate=()=>{setEditing(null);setName("");setModules(["retail"]);setBranchName("Cabang Utama");setBranchCode("UTAMA")};
  const openEdit=(business:BusinessOption)=>{setEditing(business);setName(business.name);setModules(business.modules)};
  const toggle=(id:string)=>setModules(current=>current.includes(id)?current.length>1?current.filter(item=>item!==id):current:[...current,id]);
  const saveBusiness=async()=>{if(!supabase||name.trim().length<2||modules.length===0)return localizedAlert("Usaha","Isi nama usaha dan pilih minimal satu jenis usaha.");const normalized=branchCode.trim().toUpperCase();if(editing===null&&(branchName.trim().length<2||!/^[A-Z0-9_-]{2,20}$/.test(normalized)))return localizedAlert("Usaha","Isi nama serta kode cabang awal 2–20 karakter.");setBusy(true);const result=editing?await supabase.rpc("update_business_workspace",{target_business_id:editing.id,target_name:name.trim(),enabled_modules:modules}):await supabase.rpc("create_business_workspace",{target_name:name.trim(),enabled_modules:modules,branch_name:branchName.trim(),branch_code:normalized});setBusy(false);if(result.error)return localizedAlert("Usaha",result.error.message.includes("business_name_exists")?"Nama usaha tersebut sudah digunakan.":result.error.message);setEditing(undefined);if(!editing&&typeof result.data==="string")await auth.switchBusiness(result.data);else await auth.refreshWorkspace();localizedAlert("Usaha tersimpan",editing?"Nama dan jenis usaha berhasil diperbarui.":"Usaha baru beserta cabang pertamanya berhasil dibuat.")};
  const createBranch=async()=>{if(!supabase)return;const normalized=branchCode.trim().toUpperCase();if(branchName.trim().length<2||!/^[A-Z0-9_-]{2,20}$/.test(normalized))return localizedAlert("Cabang","Isi nama dan kode cabang 2–20 karakter.");setBusy(true);const{error}=await supabase.rpc("create_business_branch",{target_business_id:workspace.businessId,target_name:branchName.trim(),target_code:normalized});setBusy(false);if(error)return localizedAlert("Cabang",error.message);await auth.refreshWorkspace();setBranchOpen(false);setBranchName("");setBranchCode("");localizedAlert("Cabang dibuat",`Cabang baru tersimpan di ${workspace.businessName}.`)};
  return <Screen><Header title="Usaha & cabang" subtitle="Kelola seluruh ruang kerja dari satu halaman" right={<Button compact variant="ghost" title="Kembali" onPress={onBack}/>}/>
    <Card><Text style={s.note}>Setiap usaha memiliki jenis modul dan daftar cabang sendiri. Transaksi, stok, shift, serta laporan tetap dipisahkan per cabang.</Text><Button title="Tambah usaha" onPress={openCreate}/></Card>
    <Text style={s.section}>DAFTAR USAHA</Text>{workspace.businesses.map(business=><Card key={business.id}><Row title={business.name} detail={business.modules.map(id=>moduleOptions.find(item=>item.id===id)?.label??id).join(" • ")} right={business.id===workspace.businessId?<Badge text="Aktif" tone="green"/>:undefined}/><View style={s.actions}>{business.id!==workspace.businessId?<Button variant="outline" title="Gunakan usaha ini" onPress={()=>void auth.switchBusiness(business.id)}/>:null}<Button variant="ghost" title="Ubah nama & jenis" onPress={()=>openEdit(business)}/></View></Card>)}
    <View style={s.sectionHead}><View style={s.flex}><Text style={s.section}>CABANG {workspace.businessName.toUpperCase()}</Text><Text style={s.note}>Cabang yang terlihat hanya milik usaha aktif.</Text></View><Button compact title="＋ Cabang" onPress={()=>{setBranchName("");setBranchCode("");setBranchOpen(true)}}/></View>
    {workspace.branches.map(branch=><Card key={branch.id}><Row title={branch.name} detail={branch.code} right={branch.id===workspace.branchId?<Badge text="Aktif" tone="green"/>:undefined}/>{branch.id!==workspace.branchId?<Button variant="outline" title="Gunakan cabang ini" onPress={()=>void auth.switchBranch(branch.id)}/>:null}</Card>)}
    <Sheet visible={editing!==undefined} title={editing?"Ubah usaha":"Tambah usaha"} onClose={()=>setEditing(undefined)}><Field label="Nama usaha" value={name} onChangeText={setName}/><Text style={s.label}>JENIS USAHA & MODUL</Text><View style={s.moduleGrid}>{moduleOptions.map(item=><Pressable key={item.id} onPress={()=>toggle(item.id)} style={[s.module,modules.includes(item.id)&&s.moduleActive]}><Text style={[s.moduleText,modules.includes(item.id)&&s.moduleTextActive]}>{modules.includes(item.id)?"✓ ":""}{item.label}</Text></Pressable>)}</View>{editing===null?<><Field label="Nama cabang pertama" value={branchName} onChangeText={setBranchName}/><Field label="Kode cabang" value={branchCode} onChangeText={value=>setBranchCode(value.toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,20))}/></>:null}<Button disabled={busy} title={busy?"Menyimpan...":"Simpan usaha"} onPress={()=>void saveBusiness()}/></Sheet>
    <Sheet visible={branchOpen} title={`Tambah cabang • ${workspace.businessName}`} onClose={()=>setBranchOpen(false)}><Field label="Nama cabang" value={branchName} onChangeText={setBranchName} placeholder="Contoh: Cabang Cirebon"/><Field label="Kode cabang" value={branchCode} onChangeText={value=>setBranchCode(value.toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,20))} placeholder="Contoh: CRB01"/><Text style={s.note}>Katalog mengikuti usaha aktif. Stok, staf, shift, transaksi, dan laporan cabang tetap terpisah.</Text><Button disabled={busy} title={busy?"Menyimpan...":"Buat cabang"} onPress={()=>void createBranch()}/></Sheet>
  </Screen>;
}
const s=StyleSheet.create({note:{fontSize:12,lineHeight:19,color:colors.muted,marginBottom:8},actions:{gap:8,marginTop:8},label:{fontSize:10,fontWeight:"900",color:colors.muted,letterSpacing:1,marginTop:4},moduleGrid:{flexDirection:"row",flexWrap:"wrap",gap:8},module:{borderWidth:1,borderColor:colors.line,borderRadius:12,paddingHorizontal:14,paddingVertical:10},moduleActive:{backgroundColor:colors.blueSoft,borderColor:colors.blue},moduleText:{fontSize:12,fontWeight:"800",color:colors.muted},moduleTextActive:{color:colors.blue},section:{fontSize:10,fontWeight:"900",letterSpacing:1,color:colors.muted},sectionHead:{flexDirection:"row",alignItems:"center",gap:12,marginTop:6},flex:{flex:1}});
