import type { Role } from "@niagacore/contracts";
import { roleCatalog, roleLabel } from "@niagacore/domain";
import React from "react";
import { Pressable, StyleSheet, View } from "react-native";

import { supabase } from "@/lib/supabase";
import type { ActiveWorkspace } from "@/providers/auth-provider";
import { Badge, Button, Card, EmptyState, Field, Header, LoadingBlock, Row, Screen, Segmented, Sheet } from "@/ui/components";
import { LocalizedText as Text, localizedAlert } from "@/ui/localized-text";
import { colors, radius } from "@/ui/theme";

type Member = { id:string; email:string; display_name:string|null; role:Role; active:boolean; branch_names:string[]; branch_ids:string[]; last_seen_at:string|null };
type Invitation = { id:string; email:string; role:Role; branch_ids:string[]; status:string; expires_at:string };
type SensitiveAction = { kind:"invite" } | { kind:"resend"; invitation:Invitation };
const staffRoles = roleCatalog.filter((item) => item.value !== "owner");

function friendlyError(message:string) {
  const map: Record<string,string> = { mfa_required:"Aktifkan dan verifikasi MFA sebelum mengubah akses staf.",pending_email:"Masih ada undangan aktif untuk email tersebut.",invalid_invitation:"Periksa email, peran, dan cabang yang dipilih.",not_configured:"Konfigurasi server undangan belum lengkap.",auth_invitation_failed:"Email undangan tidak dapat dikirim. Periksa SMTP dan rate limit Auth.",existing_account_email_failed:"Akun sudah ada, tetapi email untuk mengatur kata sandi gagal dikirim. Periksa SMTP dan rate limit Auth.",owner_required:"Sesi ini tidak memiliki izin mengelola tim.",invalid_branch_access:"Salah satu cabang tidak valid atau tidak aktif." };
  return Object.entries(map).find(([code]) => message.includes(code))?.[1] ?? message;
}
async function functionErrorMessage(error: unknown) {
  const context = (error as { context?: Response } | null)?.context;
  if (context && typeof context.clone === "function") { try { const body=await context.clone().json() as {error?:string;detail?:string;requestId?:string}; return [body.error,body.detail,body.requestId?`Referensi ${body.requestId}`:null].filter(Boolean).join(" · "); } catch { /* bawaan */ } }
  return error instanceof Error ? error.message : String(error);
}

export function StaffAccessScreen({workspace,onBack}:{workspace:ActiveWorkspace;onBack:()=>void}) {
  const [members,setMembers]=React.useState<Member[]>([]),[invites,setInvites]=React.useState<Invitation[]>([]);
  const [tab,setTab]=React.useState<"members"|"invites">("members"),[sheet,setSheet]=React.useState<"invite"|"edit"|null>(null);
  const [busy,setBusy]=React.useState(false),[loading,setLoading]=React.useState(true);
  const [mfaOpen,setMfaOpen]=React.useState(false),[mfaCode,setMfaCode]=React.useState(""),[mfaFactorId,setMfaFactorId]=React.useState(""),[pendingAction,setPendingAction]=React.useState<SensitiveAction|null>(null);
  const [email,setEmail]=React.useState(""),[role,setRole]=React.useState<Role>("cashier"),[branchIds,setBranchIds]=React.useState<string[]>([workspace.branchId]);
  const [editing,setEditing]=React.useState<Member|null>(null);
  const mayManage=["owner","business_manager"].includes(workspace.role);

  const load=React.useCallback(async()=>{
    if(!supabase)return;setLoading(true);
    try { const [memberResult,invitationResult,assurance]=await Promise.all([supabase.rpc("list_staff_access"),supabase.from("staff_invitations").select("id,email,role,branch_ids,status,expires_at").eq("tenant_id",workspace.tenantId).order("created_at",{ascending:false}),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);
      if(memberResult.error)throw memberResult.error;if(invitationResult.error)throw invitationResult.error;if(assurance.error)throw assurance.error;setMembers((memberResult.data??[]) as Member[]);setInvites((invitationResult.data??[]) as Invitation[]);
    } catch(error) { localizedAlert("Tim & akses",friendlyError(error instanceof Error?error.message:String(error))); } finally { setLoading(false); }
  },[workspace.tenantId]);
  React.useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  const openInvite=()=>{setEmail("");setRole("cashier");setBranchIds([workspace.branchId]);setEditing(null);setSheet("invite")};
  const openEdit=(member:Member)=>{setEditing(member);setRole(member.role);setBranchIds(member.branch_ids);setSheet("edit")};
  const toggleBranch=(id:string)=>setBranchIds((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
  const performInvite=async()=>{if(!supabase)return;setBusy(true);try{const targetEmail=email.trim().toLowerCase();const{data,error}=await supabase.functions.invoke("invite-staff",{body:{email:targetEmail,role,branchIds,merchantName:workspace.businessName}});if(error)throw error;setSheet(null);setTab("invites");localizedAlert("Undangan dibuat",data?.status==="existing_account_recovery_requested"?`Email akses akun sedang dikirim ke ${targetEmail}. Jika belum masuk dalam beberapa menit, periksa folder Spam atau pilih Kirim ulang.`:`Email aktivasi sedang dikirim ke ${targetEmail}. Jika belum masuk dalam beberapa menit, periksa folder Spam atau pilih Kirim ulang.`);await load()}catch(error){localizedAlert("Undangan staf",friendlyError(await functionErrorMessage(error)))}finally{setBusy(false)}};
  const saveMember=async()=>{if(!supabase||!editing||branchIds.length===0)return;setBusy(true);const{error}=await supabase.rpc("update_staff_access",{target_membership_id:editing.id,target_role:role,target_branch_ids:branchIds,target_active:editing.active});setBusy(false);if(error)return localizedAlert("Ubah akses",friendlyError(error.message));setSheet(null);await load()};
  const setActive=async(member:Member,active:boolean)=>{if(!supabase)return;const{error}=await supabase.rpc("update_staff_access",{target_membership_id:member.id,target_role:member.role,target_branch_ids:member.branch_ids,target_active:active});if(error)localizedAlert("Status staf",friendlyError(error.message));else await load()};
  const cancel=async(id:string)=>{if(!supabase)return;const{error}=await supabase.rpc("cancel_staff_invitation",{target_invitation_id:id});if(error)localizedAlert("Batalkan undangan",friendlyError(error.message));else await load()};
  const performResend=async(item:Invitation)=>{if(!supabase)return;setBusy(true);try{const cancelled=await supabase.rpc("cancel_staff_invitation",{target_invitation_id:item.id});if(cancelled.error)throw cancelled.error;const sent=await supabase.functions.invoke("invite-staff",{body:{email:item.email,role:item.role,branchIds:item.branch_ids,merchantName:workspace.businessName}});if(sent.error)throw sent.error;localizedAlert("Undangan dibuat ulang",sent.data?.status==="existing_account_recovery_requested"?`Email akses akun sedang dikirim ulang ke ${item.email}. Periksa folder Spam bila belum terlihat.`:`Email aktivasi sedang dikirim ulang ke ${item.email}. Periksa folder Spam bila belum terlihat.`);await load()}catch(error){localizedAlert("Kirim ulang",friendlyError(await functionErrorMessage(error)))}finally{setBusy(false)}};
  const executeSensitive=async(action:SensitiveAction)=>{if(action.kind==="invite")await performInvite();else await performResend(action.invitation)};
  const requireFreshMfa=async(action:SensitiveAction)=>{if(!supabase)return;const assurance=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(assurance.error)return localizedAlert("MFA",assurance.error.message);if(assurance.data.currentLevel==="aal2")return executeSensitive(action);const factors=await supabase.auth.mfa.listFactors();if(factors.error)return localizedAlert("MFA",factors.error.message);const verified=factors.data.totp.find((factor)=>factor.status==="verified");if(!verified)return localizedAlert("MFA diperlukan","Aktifkan verifikasi dua langkah di Pengaturan terlebih dahulu.");setMfaFactorId(verified.id);setMfaCode("");setPendingAction(action);setMfaOpen(true)};
  const invite=async()=>{if(!supabase||!/^\S+@\S+\.\S+$/.test(email.trim())||branchIds.length===0)return localizedAlert("Undangan staf","Email dan minimal satu cabang wajib dipilih.");await requireFreshMfa({kind:"invite"})};
  const resend=async(item:Invitation)=>{await requireFreshMfa({kind:"resend",invitation:item})};
  const verifyMfa=async()=>{if(!supabase||!pendingAction||mfaCode.length!==6)return;setBusy(true);const{error}=await supabase.auth.mfa.challengeAndVerify({factorId:mfaFactorId,code:mfaCode});setBusy(false);if(error)return localizedAlert("Verifikasi MFA",error.message);const action=pendingAction;setMfaOpen(false);setPendingAction(null);await executeSensitive(action)};

  if(!mayManage)return <Screen><Header title="Tim & akses" right={<Button compact variant="ghost" title="Kembali" onPress={onBack}/>}/><EmptyState title="Akses dibatasi" detail="Hanya pemilik atau manajer usaha yang dapat mengelola tim."/></Screen>;
  return <Screen><Header title="Tim & akses" subtitle="Peran, cabang, status, dan perangkat setiap anggota" right={<Button compact variant="ghost" title="Kembali" onPress={onBack}/>}/>
    <Card style={s.hero}><Text style={s.heroEyebrow}>AKSES BERDASARKAN PEKERJAAN</Text><Text style={s.heroTitle}>Satu akun untuk setiap anggota</Text><Text style={s.heroDetail}>Staf hanya melihat menu dan data cabang yang diberikan. Semua perubahan memiliki jejak audit.</Text><Button title="Undang anggota" onPress={openInvite}/></Card>
    <View style={s.stats}><Stat value={members.filter((item)=>item.active).length} label="Aktif"/><Stat value={invites.filter((item)=>item.status==="pending").length} label="Menunggu"/><Stat value={workspace.branches.length} label="Cabang"/></View>
    <Segmented value={tab} onChange={setTab} items={[{value:"members",label:"Anggota"},{value:"invites",label:"Undangan"}]}/>
    {loading?<LoadingBlock label="Memuat tim..."/>:tab==="members"?(members.length?members.map((item)=><Card key={item.id}><Row title={item.display_name||item.email} detail={`${item.email} · ${item.branch_names.join(", ")||"Semua cabang"}`} right={<Badge text={roleLabel(item.role)} tone={item.active?"green":"neutral"}/>} /><Text style={s.lastSeen}>{item.last_seen_at?`Perangkat terakhir aktif ${new Date(item.last_seen_at).toLocaleString("id-ID")}`:"Belum ada aktivitas perangkat"}</Text>{item.role!=="owner"&&<View style={s.actions}><Button compact variant="outline" title="Ubah akses" onPress={()=>openEdit(item)}/><Button compact variant={item.active?"danger":"primary"} title={item.active?"Tangguhkan":"Pulihkan"} onPress={()=>void setActive(item,!item.active)}/></View>}</Card>):<EmptyState title="Belum ada anggota" detail="Undang anggota dan pilih peran kerja yang sesuai."/>):(invites.length?invites.map((item)=><Card key={item.id}><Row title={item.email} detail={`${roleLabel(item.role)} · ${item.branch_ids.length} cabang · berakhir ${new Date(item.expires_at).toLocaleDateString("id-ID")}`} right={<Badge text={item.status} tone={item.status==="accepted"?"green":item.status==="pending"?"amber":"neutral"}/>} />{item.status==="pending"?<View style={s.actions}><Button compact disabled={busy} variant="outline" title="Kirim ulang" onPress={()=>void resend(item)}/><Button compact variant="ghost" title="Batalkan" onPress={()=>void cancel(item.id)}/></View>:null}</Card>):<EmptyState title="Belum ada undangan" detail="Undangan yang dikirim akan tampil di sini."/>)}
    <Sheet visible={sheet!==null} title={sheet==="edit"?"Ubah akses anggota":"Undang anggota"} onClose={()=>setSheet(null)}>{sheet==="invite"&&<Field label="Email staf" value={email} onChangeText={setEmail} keyboardType="email-address" placeholder="nama@email.com"/>}<Text style={s.label}>PERAN KERJA</Text><View style={s.roleList}>{staffRoles.map((item)=><Pressable key={item.value} onPress={()=>setRole(item.value)} style={[s.roleCard,role===item.value&&s.roleActive]}><View style={s.roleCopy}><Text style={[s.roleTitle,role===item.value&&s.roleTitleActive]}>{item.label}</Text><Text style={[s.roleSummary,role===item.value&&s.roleSummaryActive]}>{item.summary}</Text></View>{role===item.value?<Text style={s.check}>✓</Text>:null}</Pressable>)}</View><Text style={s.label}>CABANG YANG DAPAT DIAKSES</Text>{workspace.branches.map((branch)=><Pressable key={branch.id} onPress={()=>toggleBranch(branch.id)} style={[s.branch,branchIds.includes(branch.id)&&s.branchActive]}><View><Text style={s.branchName}>{branch.name}</Text><Text style={s.branchCode}>{branch.code}</Text></View><Badge text={branchIds.includes(branch.id)?"Dipilih":"Pilih"} tone={branchIds.includes(branch.id)?"blue":"neutral"}/></Pressable>)}<Button disabled={busy||branchIds.length===0} title={busy?"Menyimpan...":sheet==="edit"?"Simpan perubahan":"Kirim undangan"} onPress={()=>void(sheet==="edit"?saveMember():invite())}/></Sheet>
    <Sheet visible={mfaOpen} title="Verifikasi MFA" onClose={()=>{setMfaOpen(false);setPendingAction(null)}}><Text style={s.lastSeen}>Masukkan kode 6 digit terbaru dari aplikasi authenticator. Verifikasi ini menaikkan sesi aktif ke AAL2 sebelum tindakan sensitif dikirim ke server.</Text><Field label="Kode authenticator" value={mfaCode} onChangeText={(value)=>setMfaCode(value.replace(/\D/g,"").slice(0,6))} keyboardType="numeric" placeholder="000000"/><Button disabled={busy||mfaCode.length!==6} title={busy?"Memverifikasi...":"Verifikasi & lanjutkan"} onPress={()=>void verifyMfa()}/></Sheet>
  </Screen>;
}
function Stat({value,label}:{value:number;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({hero:{backgroundColor:colors.navy,borderColor:colors.navy,gap:8},heroEyebrow:{color:"#8DB5FF",fontSize:9,fontWeight:"900",letterSpacing:1.2},heroTitle:{color:colors.white,fontSize:20,fontWeight:"900"},heroDetail:{color:"#D7E2F5",fontSize:12,lineHeight:18,marginBottom:6},stats:{flexDirection:"row",gap:8},stat:{flex:1,padding:12,borderRadius:radius.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},statValue:{color:colors.ink,fontSize:20,fontWeight:"900"},statLabel:{color:colors.muted,fontSize:10,marginTop:2},lastSeen:{fontSize:10,color:colors.muted,marginTop:8},actions:{flexDirection:"row",justifyContent:"flex-end",gap:8,marginTop:10},label:{fontSize:10,fontWeight:"900",letterSpacing:1,color:colors.muted,marginTop:4},roleList:{gap:7},roleCard:{minHeight:58,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:11,flexDirection:"row",alignItems:"center",backgroundColor:colors.surface},roleActive:{backgroundColor:colors.blue,borderColor:colors.blue},roleCopy:{flex:1},roleTitle:{fontSize:13,fontWeight:"900",color:colors.ink},roleTitleActive:{color:colors.white},roleSummary:{fontSize:10,color:colors.muted,marginTop:2},roleSummaryActive:{color:"#DCE8FF"},check:{color:colors.white,fontSize:18,fontWeight:"900"},branch:{minHeight:58,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:11,flexDirection:"row",alignItems:"center",justifyContent:"space-between",backgroundColor:colors.surface},branchActive:{borderColor:colors.blue,backgroundColor:colors.blueSoft},branchName:{fontSize:13,fontWeight:"900",color:colors.ink},branchCode:{fontSize:10,color:colors.muted,marginTop:2}});
