export type IndonesianBank = { code: string; name: string; aliases?: string };

// Bank umum konvensional, digital, dan syariah yang lazim menerima transfer
// domestik. Kode disimpan sebagai identifier; nama ditampilkan kepada pengguna.
export const indonesianBanks: IndonesianBank[] = [
  { code: "BCA", name: "Bank Central Asia", aliases: "BCA" },
  { code: "MANDIRI", name: "Bank Mandiri" },
  { code: "BRI", name: "Bank Rakyat Indonesia" },
  { code: "BNI", name: "Bank Negara Indonesia" },
  { code: "BTN", name: "Bank Tabungan Negara" },
  { code: "BSI", name: "Bank Syariah Indonesia" },
  { code: "CIMB", name: "CIMB Niaga" },
  { code: "DANAMON", name: "Bank Danamon" },
  { code: "PERMATA", name: "PermataBank" },
  { code: "PANIN", name: "PaninBank" },
  { code: "OCBC", name: "OCBC Indonesia", aliases: "NISP" },
  { code: "MAYBANK", name: "Maybank Indonesia" },
  { code: "MEGA", name: "Bank Mega" },
  { code: "SINARMAS", name: "Bank Sinarmas" },
  { code: "BUKOPIN", name: "KB Bank", aliases: "Bukopin" },
  { code: "BTPN", name: "Bank SMBC Indonesia", aliases: "BTPN Jenius" },
  { code: "JAGO", name: "Bank Jago" },
  { code: "NEO", name: "Bank Neo Commerce" },
  { code: "SEABANK", name: "SeaBank Indonesia" },
  { code: "ALLO", name: "Allo Bank Indonesia" },
  { code: "HIBANK", name: "hibank Indonesia" },
  { code: "SAHABAT_SAMPOERNA", name: "Bank Sahabat Sampoerna" },
  { code: "UOB", name: "UOB Indonesia" },
  { code: "DBS", name: "Bank DBS Indonesia" },
  { code: "HSBC", name: "HSBC Indonesia" },
  { code: "STANDARD_CHARTERED", name: "Standard Chartered Indonesia" },
  { code: "AMAR", name: "Amar Bank" },
  { code: "INA", name: "Bank Ina Perdana" },
  { code: "GANESHA", name: "Bank Ganesha" },
  { code: "MASPION", name: "Bank Maspion Indonesia" },
  { code: "INDEX", name: "Bank Index Selindo" },
  { code: "CAPITAL", name: "Bank Capital Indonesia" },
  { code: "MNC", name: "MotionBank", aliases: "MNC Bank" },
  { code: "VICTORIA", name: "Bank Victoria International" },
  { code: "QNB", name: "Bank QNB Indonesia" },
  { code: "JTRUST", name: "Bank JTrust Indonesia" },
  { code: "SBI", name: "Bank SBI Indonesia" },
  { code: "WOORI", name: "Bank Woori Saudara" },
  { code: "IBK", name: "Bank IBK Indonesia" },
  { code: "SHINHAN", name: "Bank Shinhan Indonesia" },
  { code: "HANA", name: "Hana Bank Indonesia", aliases: "KEB Hana" },
  { code: "MIZUHO", name: "Bank Mizuho Indonesia" },
  { code: "RESONA", name: "Bank Resona Perdania" },
  { code: "CCB", name: "Bank China Construction Bank Indonesia" },
  { code: "BOC", name: "Bank of China Indonesia" },
  { code: "ICBC", name: "Bank ICBC Indonesia" },
  { code: "MUAMALAT", name: "Bank Muamalat Indonesia" },
  { code: "MEGA_SYARIAH", name: "Bank Mega Syariah" },
  { code: "BCA_SYARIAH", name: "BCA Syariah" },
  { code: "PANIN_DUBAI_SYARIAH", name: "Panin Dubai Syariah" },
  { code: "KB_BUKOPIN_SYARIAH", name: "KB Bukopin Syariah" },
  { code: "BTPN_SYARIAH", name: "BTPN Syariah" },
  { code: "VICTORIA_SYARIAH", name: "Bank Victoria Syariah" },
  { code: "ALADIN", name: "Bank Aladin Syariah" },
  { code: "JABAR_BANTEN", name: "Bank BJB" },
  { code: "DKI", name: "Bank DKI" },
  { code: "BPD_DIY", name: "Bank BPD DIY" },
  { code: "JATENG", name: "Bank Jateng" },
  { code: "JATIM", name: "Bank Jatim" },
  { code: "SUMUT", name: "Bank Sumut" },
  { code: "NAGARI", name: "Bank Nagari" },
  { code: "RIAU_KEPRI", name: "Bank Riau Kepri Syariah" },
  { code: "SUMSEL_BABEL", name: "Bank Sumsel Babel" },
  { code: "LAMPUNG", name: "Bank Lampung" },
  { code: "KALSEL", name: "Bank Kalsel" },
  { code: "KALBAR", name: "Bank Kalbar" },
  { code: "KALTIMTARA", name: "Bank Kaltimtara" },
  { code: "KALTENG", name: "Bank Kalteng" },
  { code: "SULSELBAR", name: "Bank Sulselbar" },
  { code: "SULUTGO", name: "Bank SulutGo" },
  { code: "SULTENG", name: "Bank Sulteng" },
  { code: "SULTRA", name: "Bank Sultra" },
  { code: "PAPUA", name: "Bank Papua" },
  { code: "MALUKU_MALUT", name: "Bank Maluku Malut" },
  { code: "NTB_SYARIAH", name: "Bank NTB Syariah" },
  { code: "NTT", name: "Bank NTT" },
  { code: "BALI", name: "Bank BPD Bali" },
  { code: "BENGKULU", name: "Bank Bengkulu" },
  { code: "JAMBI", name: "Bank Jambi" },
];

export function bankName(code: string): string {
  return indonesianBanks.find((bank) => bank.code === code)?.name ?? code;
}
