import React from "react";
import { Alert, StyleSheet, Text as NativeText, type AlertButton, type TextProps } from "react-native";

import { i18n } from "@/lib/i18n";
import { useAppTheme } from "@/providers/theme-provider";

const exact: Record<string, string> = {
  "Beranda": "Home", "Kasir": "POS", "Produk": "Products", "Laporan": "Reports", "Lainnya": "More",
  "Pemilik": "Owner", "Manajer usaha": "Business manager", "Kepala cabang": "Branch manager",
  "Supervisor": "Supervisor", "Gudang": "Warehouse",
  "Staf layanan": "Service staff", "Dapur": "Kitchen", "Pramusaji": "Waiter",
  "Auditor": "Auditor", "Pelanggan": "Customers", "Pemasok": "Suppliers",
  "Pengaturan": "Settings", "Operasional": "Operations", "Keuangan": "Finance", "Akuntansi": "Accounting",
  "Persediaan": "Inventory", "Pembelian": "Purchasing", "Pengaturan usaha & akuntansi": "Business & accounting settings",
  "Pengaturan akun & perangkat": "Account & device settings", "Riwayat": "History", "Jumlah transaksi": "Transaction count",
  "Rata-rata": "Average", "Semua cabang": "All branches", "Data gagal dimuat": "Failed to load data",
  "Kembali": "Back", "Tutup": "Close", "Batal": "Cancel", "Lanjutkan": "Continue", "Simpan": "Save",
  "Arsipkan": "Archive", "Aktif": "Active", "Terkunci": "Locked", "Eksperimental": "Experimental",
  "Terverifikasi": "Verified", "Dalam tinjauan": "Under review", "Sehat": "Healthy", "Aktual": "Actual",
  "Nama / judul": "Name / title", "Nomor / kode": "Number / code", "Keterangan": "Description",
  "Nama produk": "Product name", "Kategori": "Category", "Harga": "Price", "Stok": "Stock",
  "Foto produk": "Product photo", "Pilih foto": "Choose photo", "Ganti foto": "Change photo", "Hapus": "Remove",
  "Pilih produk": "Choose a product", "Hitung penyusutan": "Calculate depreciation",
  "Siapkan data pajak": "Prepare tax data", "Simpan rekening": "Save bank account",
  "Lihat kata sandi": "Show password", "Sembunyikan kata sandi": "Hide password", "LIHAT": "SHOW", "SEMBUNYIKAN": "HIDE",
  "Simpan produk": "Save product", "Tambah produk": "Add product", "Edit produk": "Edit product",
  "Riwayat, retur & pembatalan": "History, returns & cancellations", "Transaksi": "Transactions",
  "Tren penjualan": "Sales trend", "Produk teratas": "Top products", "Metode pembayaran": "Payment methods",
  "Laba estimasi": "Estimated profit", "Piutang": "Receivables", "Utang": "Payables", "Stok menipis": "Low stock",
  "Penjualan": "Sales", "HPP": "COGS", "Beban": "Expenses", "Tunai": "Cash", "Total": "Total",
  "Ringkas": "Overview", "Laba rugi": "Profit & loss", "Neraca": "Balance sheet", "Detail": "Details",
  "Arus kas langsung": "Direct cash flow", "Kas masuk": "Cash inflow",
  "Kas keluar": "Cash outflow", "Arus kas bersih": "Net cash flow", "Persediaan & pajak": "Inventory & tax",
  "Nilai persediaan": "Inventory value", "Pajak keluaran": "Output tax", "Pajak masukan": "Input tax",
  "Rekonsiliasi pajak": "Tax reconciliation", "Belum jatuh tempo": "Not yet due", "Laporan laba rugi": "Profit and loss statement",
  "Pendapatan": "Revenue", "Beban dan HPP": "Expenses and COGS", "Laba (rugi) bersih": "Net profit (loss)",
  "Total aset": "Total assets", "Total liabilitas": "Total liabilities", "Ekuitas": "Equity", "Kas": "Cash",
  "Neraca saldo": "Trial balance", "Neraca seimbang": "Balance sheet balanced", "Perlu rekonsiliasi": "Reconciliation required",
  "Membantu": "Helpful", "Keliru": "Incorrect", "Analisis usaha": "Business analysis", "Prediksi stok": "Stock forecast",
  "Deteksi anomali": "Anomaly detection", "Ringkasan keuangan": "Financial summary", "Analisis penjualan": "Sales analysis",
  "Pola pelanggan": "Customer patterns", "TEMA APLIKASI": "APP THEME", "Perangkat": "Device", "Terang": "Light", "Gelap": "Dark",
  "Tanya NIA": "Ask NIA", "Tanyakan": "Ask", "DASAR ANALISIS": "ANALYSIS BASIS",
  "Tanya, pahami, lalu ambil keputusan": "Ask, understand, then decide", "Pilih kebutuhan": "Choose a task",
  "Ringkasan usaha": "Business overview", "Periksa risiko": "Check risks",
  "Layanan NIA perlu diperbarui": "NIA service needs an update", "Coba lagi": "Try again", "HASIL NIA": "NIA RESULT",
  "MESIN KEPUTUSAN NIA": "NIA DECISION ENGINES", "Data terverifikasi": "Verified data",
  "Statistical ML": "Statistical ML", "Customer RFM": "Customer RFM", "Hybrid RAG": "Hybrid RAG",
  "LLM penjelas": "LLM explainer", "Prediksi & pemesanan": "Forecasting & replenishment",
  "Aturan & robust MAD": "Rules & robust MAD", "Segmentasi pelanggan": "Customer segmentation",
  "Panduan & kebijakan": "Guidance & policies", "Gemini + Cloudflare": "Gemini + Cloudflare",
  "AKTIF": "ACTIVE", "SIAP": "READY", "PERLU SUMBER": "SOURCE REQUIRED", "SIAGA": "STANDBY",
  "LAPISAN PENJELAS AI": "AI EXPLANATION LAYER", "Pilih analisis": "Choose an analysis",
  "Basis pengetahuan NIA": "NIA knowledge base", "RAG & EMBEDDINGS": "RAG & EMBEDDINGS",
  "Kelola panduan dan kebijakan usaha": "Manage business guidance and policies",
  "Tambah panduan atau kebijakan": "Add guidance or policy", "Judul": "Title", "Isi panduan": "Guidance content",
  "Berlaku untuk semua cabang": "Apply to all branches", "Simpan ke basis pengetahuan": "Save to knowledge base",
  "Membuat embedding...": "Creating embedding...", "Dokumen aktif": "Active documents", "Belum ada panduan": "No guidance yet",
  "DATA TRANSAKSI": "TRANSACTION DATA", "Gunakan cabang ini": "Use this branch",
  "Menganalisis...": "Analyzing...", "Semua data tersinkron": "All data synced", "Perubahan menunggu sinkron": "Changes awaiting sync",
  "Sinkronisasi perlu perhatian": "Sync needs attention", "QRIS terkunci": "QRIS locked", "Pembayaran tunai tetap aktif": "Cash payments remain active",
  "Periode pertama": "First period", "Rata-rata transaksi": "Average ticket", "Periode sebelumnya": "Previous period",
  "7 hari": "7 days", "30 hari": "30 days", "90 hari": "90 days", "Tren periode": "Period trend",
  "Tidak ada konflik terbuka": "No open conflicts", "Gunakan server": "Use server", "Keluar dari akun": "Sign out",
  "Bahasa aplikasi": "App language", "Perangkat kasir": "POS devices", "Segarkan status merchant": "Refresh merchant status",
  "PPN aktif": "VAT enabled", "PROFIL PAJAK": "TAX PROFILE", "METODE HPP": "COGS METHOD", "STOK TIDAK CUKUP": "INSUFFICIENT STOCK",
  "Blokir": "Block", "Izinkan": "Allow", "Approval": "Approval", "AI cloud": "Cloud AI",
  "MFA authenticator": "Authenticator MFA", "Belum aktif": "Not active", "Aktifkan MFA": "Enable MFA",
  "Periksa formulir": "Check the form", "STATUS WORKFLOW": "WORKFLOW STATUS", "Belum ada pembayaran.": "No payments yet.",
  "Belum ada jurnal terposting.": "No posted journals yet.", "Belum ada penjualan pada periode ini.": "No sales in this period.",
  "Belum ada transaksi pada periode ini.": "No transactions in this period.", "Data saat ini": "Current data",
  "Relasi": "Relationships", "Katalog": "Catalog", "Jasa": "Services",
  "Pesanan pembelian": "Purchase orders", "Penerimaan barang": "Goods receipts", "Tagihan pemasok": "Supplier bills",
  "Retur pembelian": "Purchase returns", "Utang usaha": "Accounts payable", "Piutang usaha": "Accounts receivable",
  "Jurnal manual": "Manual journals", "Periode akuntansi": "Accounting periods", "Aset tetap": "Fixed assets",
  "Stok opname": "Stock counts", "Transfer stok": "Stock transfers", "Batch & kedaluwarsa": "Lots & expiry",
  "Daftar harga": "Price lists", "Bundel produk": "Product bundles", "Resep / BOM": "Recipe / BOM",
  "Meja": "Tables", "Pesanan dapur": "Kitchen orders", "Jadwal layanan": "Appointments",
  "Segmen pelanggan": "Customer segments", "Loyalitas": "Loyalty", "Staf & akses": "Staff & access",
  "Riwayat penjualan": "Sales history", "Pindai barcode": "Scan barcode", "Pindai nota / invoice": "Scan receipt / invoice",
  "Riwayat Transaksi": "Transaction History", "Filter jumlah transaksi, omzet, visualisasi, dan struk": "Filter transaction count, revenue, charts, and receipts",
  "1 hari": "1 day", "TRANSAKSI": "TRANSACTIONS", "OMZET": "REVENUE", "RATA-RATA": "AVERAGE", "RETUR": "REFUNDS",
  "Tren transaksi": "Transaction trend", "Omzet": "Revenue",
  "Hasil pembacaan": "Recognition result", "Gunakan hasil": "Use result", "Foto ulang": "Retake photo",
  "Ambil foto & baca": "Take photo & recognize", "Membaca dokumen...": "Reading document...", "Izinkan kamera": "Allow camera",
  "OCR gagal": "OCR failed", "Dokumen tidak dapat dibaca.": "The document could not be read.", "Foto tidak tersedia.": "Photo is unavailable.",
  "Teks tidak terdeteksi. Coba pencahayaan yang lebih terang.": "No text was detected. Try brighter lighting.",
  "Produk & stok": "Products & inventory", "Produk baru": "New product", "Barang": "Goods", "Resep": "Recipe",
  "Stok rendah": "Low stock", "Tersedia": "Available", "Produk tidak ditemukan": "Product not found",
  "Deskripsi": "Description", "Harga jual": "Selling price", "HPP awal": "Initial COGS", "Stok awal": "Opening stock",
  "Stok saat ini": "Current stock", "Stok minimum": "Minimum stock", "Satuan": "Unit", "Pajak %": "Tax %",
  "Lacak persediaan": "Track inventory", "Izinkan stok minus item": "Allow negative stock for this item",
  "Sesuaikan stok": "Adjust stock", "Penyesuaian stok": "Stock adjustment", "Perubahan kuantitas": "Quantity change",
  "Alasan wajib": "Reason required", "Simpan penyesuaian": "Save adjustment", "Pilih pelanggan": "Select customer",
  "Umum / tanpa pelanggan": "General / no customer", "Buka shift": "Open shift", "Tutup shift": "Close shift",
  "Saldo kas awal": "Opening cash", "Kas aktual": "Actual cash", "Hitung & tutup shift": "Calculate & close shift",
  "Kas masuk / keluar": "Cash in / out", "Modal kas": "Cash float", "Catatan": "Notes", "Riwayat transaksi": "Transaction history",
  "Belum ada transaksi": "No transactions yet", "Retur transaksi": "Transaction refund", "Nominal retur": "Refund amount",
  "Kembali ke stok": "Return to stock", "Rusak / tidak layak": "Damaged / unsellable", "Proses retur": "Process refund",
  "Lihat laporan": "View reports", "Data akan muncul setelah transaksi pertama.": "Data will appear after the first transaction.",
  "Konfigurasi production diperlukan": "Production configuration required", "Profil usaha": "Business profile",
  "Masuk": "Sign in", "Daftar": "Register", "Kata sandi": "Password", "Buat akun merchant": "Create merchant account",
  "Buat akun baru": "Create a new account", "Sudah punya akun": "Already have an account", "Gunakan akun lain": "Use another account",
  "Nama lengkap pemilik": "Owner full name", "Nama organisasi": "Organization name", "Nama usaha": "Business name",
  "Cabang pertama": "First branch", "Kode cabang": "Branch code", "MODUL USAHA": "BUSINESS MODULES", "Buat usaha": "Create business",
  "Memuat...": "Loading...", "Proses berhasil": "Completed successfully", "Gagal menyimpan": "Failed to save",
  "Kasir perlu membuka shift sebelum memulai transaksi.": "The cashier must open a shift before starting a transaction.",
  "Pilih produk untuk memulai transaksi.": "Select a product to start a transaction.",
  "Kebijakan usaha memblokir penjualan stok minus.": "Business policy blocks sales with insufficient stock.",
  "Supervisor/pemilik dapat menyetujui penjualan stok minus. Tindakan ini dicatat untuk rekonsiliasi.": "A supervisor or owner may approve an insufficient-stock sale. The action is recorded for reconciliation.",
  "Transaksi diblokir. Minta persetujuan supervisor atau pemilik.": "Transaction blocked. Ask a supervisor or owner for approval.",
  "QRIS menunggu verifikasi merchant dan aktivasi resmi Midtrans.": "QRIS is awaiting merchant verification and official Midtrans activation.",
  "Status pembayaran gateway hanya dapat ditetapkan oleh webhook server Midtrans.": "Gateway payment status can only be finalized by the Midtrans server webhook.",
  "Nominal dan alasan retur wajib valid.": "A valid refund amount and reason are required.",
  "Kasir mengajukan retur untuk persetujuan.": "Cashiers submit refunds for approval.",
  "Supervisor/pemilik dapat menyetujui retur langsung. Koreksi dibuat sebagai event baru.": "Supervisors and owners can approve refunds directly. Corrections are recorded as new events.",
  "Retur diposting dan jurnal koreksi akan disinkronkan.": "The refund is posted and its correction journal will be synchronized.",
  "Permintaan menunggu persetujuan supervisor/pemilik.": "The request is awaiting supervisor or owner approval.",
  "Backend diperlukan untuk memproses refund QRIS.": "The backend is required to process a QRIS refund.",
  "Status refund dicatat oleh server Midtrans.": "Refund status is recorded by the Midtrans server.",
  "Tambahkan produk pertama atau ubah kata pencarian.": "Add your first product or change the search term.",
  "Nama, SKU, harga, stok, dan pajak harus valid.": "Name, SKU, price, stock, and tax must be valid.",
  "Nonaktif untuk jasa atau item non-stok.": "Disable for services or non-stock items.",
  "Tetap tunduk pada kebijakan dan approval usaha.": "Still subject to business policy and approval.",
  "Perubahan stok dicatat melalui ledger penyesuaian agar dapat diaudit.": "Stock changes are recorded through an adjustment ledger for auditability.",
  "Nilai positif menambah stok, nilai negatif mengurangi stok. Catatan tidak dapat dihapus dari jejak audit.": "Positive values add stock and negative values reduce it. The record cannot be removed from the audit trail.",
  "AI cloud dinonaktifkan oleh pemilik pada pengaturan usaha.": "Cloud AI has been disabled by the owner in business settings.",
  "Backend belum dikonfigurasi.": "The backend is not configured.",
  "Transaksi yang selesai akan muncul di sini.": "Completed transactions will appear here.",
  "Konektor tersedia sebagai adapter; belum berstatus supported sebelum uji fisik.": "Connectors are available as adapters and remain unsupported until physical testing passes.",
  "Penghapusan faktor harus melalui proses re-authentication dan halaman keamanan akun.": "Factor removal requires re-authentication through the account security page.",
  "Perangkat akan dikunci dan data lokal dihapus aman saat kembali online.": "The device will be locked and local data securely removed when it reconnects.",
  "Mode demo sudah dihapus. Masukkan URL dan anon key Supabase pada environment EAS, terapkan seluruh migrasi, lalu buat APK baru.": "Demo mode has been removed. Configure the Supabase URL and anon key in the EAS environment, apply every migration, then build a new APK.",
  "Saldo Merchant": "Merchant Balance", "Pusat Struk": "Receipt Center", "Undang staf": "Invite staff",
  "Saldo merchant": "Merchant balance", "Pending": "Pending", "Reserve": "Reserve", "Dikunci": "Locked",
  "Penarikan dana": "Withdrawals", "Tambah rekening": "Add bank account", "Tarik dana": "Withdraw funds",
  "Permintaan terakhir": "Recent requests", "Mutasi saldo": "Balance activity", "Tambah rekening bank": "Add bank account",
  "Nama pemilik rekening": "Account holder", "Nomor rekening": "Account number",
  "Ajukan penarikan": "Request withdrawal", "Saldo tersedia": "Available balance", "Nominal": "Amount",
  "Anggota aktif": "Active members", "Undangan": "Invitations", "Undangan staf": "Staff invitation",
  "Email staf": "Staff email", "Kirim undangan aman": "Send secure invitation", "Cabut": "Revoke",
  "Pin perangkat": "Device PIN", "Pusat struk": "Receipt center", "Cetak / Bagikan struk QR": "Print / Share QR receipt",
  "Bayar dengan QRIS": "Pay with QRIS", "Nomor struk": "Receipt number", "Periksa pembayaran": "Check payment",
  "Pembayaran berhasil": "Payment successful", "Bagikan PDF": "Share PDF", "Cetak struk": "Print receipt",
  "Menunggu pembayaran": "Awaiting payment", "QRIS kedaluwarsa": "QRIS expired", "Segarkan status": "Refresh status",
  "PENARIKAN DANA": "WITHDRAWALS", "PERMINTAAN TERAKHIR": "RECENT REQUESTS", "MUTASI SALDO": "BALANCE ACTIVITY",
  "PERAN BERBEDA, DATA YANG SAMA": "DIFFERENT ROLES, SHARED BUSINESS DATA", "ANGGOTA AKTIF": "ACTIVE MEMBERS",
  "UNDANGAN": "INVITATIONS", "PIN PERANGKAT": "DEVICE PIN", "Belum ada undangan staf.": "No staff invitations yet.",
  "Belum ada permintaan penarikan.": "No withdrawal requests yet.", "Belum ada struk": "No receipts yet",
  "Mutasi akan muncul setelah pembayaran QRIS settlement.": "Balance activity appears after QRIS settlement.",
  "Akses pemilik diperlukan": "Owner access required",
  "Atur PIN perangkat": "Set device PIN", "PIN perangkat": "Device PIN", "PIN 6 digit": "6-digit PIN",
  "Ulangi PIN": "Repeat PIN", "Simpan PIN aman": "Save secure PIN",
  "Gunakan 6 digit yang sama pada kedua kolom.": "Enter the same 6 digits in both fields.",
  "PIN perangkat berhasil diperbarui.": "The device PIN was updated.",
  "NiagaCore terkunci": "NiagaCore is locked", "Masukkan PIN perangkat untuk melanjutkan sesi aktif.": "Enter the device PIN to continue the active session.",
  "Masukkan PIN 6 digit.": "Enter the 6-digit PIN.", "PIN salah atau sementara dikunci.": "The PIN is incorrect or temporarily locked.",
  "Buka aplikasi": "Unlock app", "Memeriksa...": "Checking...", "RUANG KERJA AKTIF": "ACTIVE WORKSPACE",
  "Hanya data dan tindakan yang sesuai dengan peran Anda yang ditampilkan.": "Only data and actions allowed for your role are shown.",
  "Verifikasi dua langkah": "Two-step verification", "Aktifkan verifikasi dua langkah": "Enable two-step verification",
  "Tindakan akuntansi": "Accounting actions", "Posting penyusutan": "Post depreciation", "Ekspor pajak": "Export tax",
  "Baris jurnal": "Journal lines", "BARIS JURNAL": "JOURNAL LINES", "Belum seimbang": "Not balanced", "Seimbang": "Balanced",
  "Tambah baris jurnal": "Add journal line", "Debit": "Debit", "Kredit": "Credit",
  "Komponen produk": "Product components", "Bahan resep": "Recipe ingredients", "KOMPONEN BUNDEL": "BUNDLE COMPONENTS", "BAHAN RESEP": "RECIPE INGREDIENTS",
  "Versi kebijakan": "Policy version", "Kode pemetaan ekspor Coretax": "Coretax export mapping code",
  "Pertahankan server": "Keep server version", "perlu ditinjau": "requires review",
  "Total debit dan kredit harus sama serta lebih dari nol.": "Total debits and credits must match and be greater than zero.",
  "Jurnal membutuhkan minimal dua baris.": "A journal requires at least two lines.",
};

const domainToId: Record<string, string> = {
  owner: "Pemilik", business_manager:"Manajer usaha", branch_manager:"Kepala cabang", supervisor: "Supervisor", cashier: "Kasir",
  warehouse:"Gudang", purchasing:"Pembelian", finance:"Keuangan", service_staff:"Staf layanan", kitchen:"Dapur", waiter:"Pramusaji", auditor:"Auditor",
  pending: "Menunggu", approved: "Disetujui",
  rejected: "Ditolak", suspended: "Ditangguhkan", active: "Aktif", inactive: "Nonaktif", draft: "Draf",
  submitted: "Diajukan", posted: "Terposting", paid: "Dibayar", void: "Dibatalkan", refunded: "Diretur",
  open: "Terbuka", closed: "Ditutup", completed: "Selesai", cancelled: "Dibatalkan", supported: "Didukung",
  experimental: "Eksperimental", deprecated: "Tidak digunakan", cash: "Tunai", transfer: "Transfer", card: "Kartu",
  credit: "Kredit", qris: "QRIS", goods: "Barang", service: "Jasa", recipe: "Resep", bundle: "Bundel",
};

const englishToId: Record<string, string> = {
  "customer, time, and status":"Pelanggan, waktu, dan status",
  "goods returned to suppliers":"Barang dikembalikan ke pemasok",
  "history, returns & cancellations":"Riwayat, retur & pembatalan",
  "off by default; enable only after tax status review":"Default nonaktif; aktifkan hanya setelah peninjauan status pajak",
  "operational alerts and status":"Peringatan operasional dan status",
  "purchase orders and approval status":"Pesanan pembelian dan status persetujuan",
  "purchase returns":"Retur pembelian",
  "queue and serving status":"Antrean dan status penyajian",
  "refresh merchant status":"Segarkan status merchant",
  "return to stock":"Kembali ke stok",
  "table capacity and status":"Kapasitas dan status meja",
};

const phrases: [string, string][] = [
  ["Ketuk produk untuk menambahkannya ke keranjang", "Tap a product to add it to the cart"],
  ["Hitung penyusutan aset atau siapkan data pajak untuk periode yang sedang dipilih", "Calculate asset depreciation or prepare tax data for the selected period"],
  ["Pemeriksaan pembaruan belum tersedia. Silakan coba kembali setelah layanan rilis aktif", "Update checks are not available yet. Please try again after the release service is active"],
  ["Perubahan tersinkron otomatis saat koneksi tersedia. Jika ada data yang perlu ditinjau, langkah penyelesaiannya akan muncul di bagian ini", "Changes sync automatically when a connection is available. If data needs review, the resolution steps will appear here"],
  ["Data yang disimpan akan tersedia di perangkat lain sesuai akses pengguna", "Saved data will be available on other devices according to user access"],
  ["Data pelanggan dan riwayat belanja", "Customer data and purchase history"],
  ["Data pemasok dan transaksi pembelian", "Supplier data and purchase transactions"],
  ["Buat dan pantau pesanan ke pemasok", "Create and track supplier orders"],
  ["Catat tagihan dan tanggal pembayaran", "Record bills and payment dates"],
  ["Catat transaksi akuntansi lainnya", "Record other accounting transactions"],
  ["Atur periode pencatatan laporan", "Set reporting periods"],
  ["Atur jenis dan tarif pajak usaha", "Set business tax types and rates"],
  ["Cocokkan stok aplikasi dengan stok fisik", "Reconcile app inventory with physical stock"],
  ["Atur harga eceran, grosir, dan khusus", "Set retail, wholesale, and special prices"],
  ["Atur bahan baku dan takaran menu", "Set menu ingredients and quantities"],
  ["Kelompokkan pelanggan berdasarkan aktivitas", "Group customers by activity"],
  ["Atur peran dan akses setiap cabang", "Set roles and access for each branch"],
  ["Nomor rekening disimpan dengan aman. Setelah tersimpan, aplikasi hanya menampilkan empat digit terakhir", "The bank account number is stored securely. After saving, the app only shows the last four digits"],
  ["Layanan rekening belum aktif sepenuhnya. Selesaikan konfigurasi keamanan server lalu coba kembali", "The bank account service is not fully active. Complete the server security configuration and try again"],
  ["Layanan rekening belum aktif. Jalankan skrip konfigurasi server, lalu coba kembali", "The bank account service is not active. Run the server configuration script, then try again"],
  ["Konfigurasi keamanan rekening belum valid. Jalankan ulang skrip konfigurasi server", "The bank account security configuration is invalid. Run the server configuration script again"],
  ["Semua modul usaha dalam satu pusat kerja", "All business modules in one workspace"],
  ["Telusuri transaksi dan ajukan koreksi terkontrol", "Review transactions and submit controlled corrections"],
  ["Buat data pertama untuk mulai menggunakan modul ini", "Create the first record to start using this module"],
  ["Belum ada", "No"], ["Tambah", "Add"], ["Edit", "Edit"], ["Jatuh tempo", "Due"],
  ["hari", "days"], ["unit", "units"], ["Wajib diisi", "Required"], ["wajib diisi", "is required"],
  ["harus berupa angka valid", "must be a valid number"], ["harus memakai format", "must use format"],
  ["Nama atau judul minimal 2 karakter", "Name or title must contain at least 2 characters"],
  ["Angka dihitung dari transaksi dan jurnal tersimpan", "Figures are calculated from saved transactions and journals"],
  ["Sumbu vertikal menunjukkan nilai penjualan, sumbu horizontal menunjukkan tanggal", "The vertical axis shows sales value and the horizontal axis shows dates"],
  ["Penjualan tersimpan pada perangkat", "Sales stored on this device"],
  ["Data aktual • dibanding periode sebelumnya", "Actual data • compared with the previous period"],
  ["Berdasarkan pendapatan", "By revenue"], ["Berdasarkan data usaha, bukan data contoh", "Based on business data, not sample data"],
  ["Minta ringkasan keuangan, prediksi stok, anomali, atau rekomendasi penjualan", "Request a financial summary, stock forecast, anomalies, or sales recommendations"],
  ["AI tidak dapat mengubah transaksi, stok, pembayaran, maupun jurnal", "AI cannot change transactions, stock, payments, or journals"],
  ["Apakah analisis ini membantu?", "Was this analysis helpful?"], ["antrean • ketuk untuk sinkron sekarang", "queued • tap to sync now"],
  ["QRIS baru dapat digunakan setelah merchant terverifikasi dan aktivasi Midtrans resmi selesai", "QRIS becomes available after merchant verification and official Midtrans activation"],
  ["Usaha, keamanan, akuntansi, dan perangkat", "Business, security, accounting, and devices"],
  ["Menunggu verifikasi dan aktivasi Midtrans", "Awaiting verification and Midtrans activation"],
  ["Pembayaran gateway aktif", "Gateway payments active"], ["Faktor TOTP sudah terdaftar", "TOTP factor is enrolled"],
  ["Wajib sebelum tindakan sensitif dan production", "Required before sensitive production actions"],
  ["Default nonaktif; aktifkan hanya sesuai status dan review pajak", "Off by default; enable only after tax status review"],
  ["Default Approval: diblokir untuk kasir, supervisor/pemilik dapat menyetujui dengan audit log", "Approval default: blocked for cashiers; supervisors/owners may approve with an audit trail"],
  ["Tanpa kuota merchant selama fase gratis; backend tetap memakai proteksi penyalahgunaan", "No merchant quota during the free phase; backend abuse protection remains active"],
  ["Perubahan lokal dan server sudah konsisten", "Local and server changes are consistent"],
  ["Versi server dipertahankan", "The server version is retained"], ["Selesaikan konflik", "Resolve conflict"],
  ["pada periode ini", "in this period"], ["Tandai", "Mark"], ["Aktifkan", "Enable"], ["Nonaktifkan", "Disable"],
  ["Setujui", "Approve"], ["Ajukan", "Submit"], ["Selesaikan", "Complete"], ["Batalkan", "Cancel"],
  ["Pemilik", "Owner"], ["Supervisor", "Supervisor"], ["Kasir", "Cashier"], ["Pelanggan", "Customer"],
  ["Pemasok", "Supplier"], ["Produk", "Product"], ["Pembayaran", "Payment"], ["Tanggal", "Date"],
  ["Jumlah", "Quantity"], ["Harga", "Price"], ["Akun", "Account"], ["Cabang", "Branch"],
  ["Peringatan", "Warning"], ["Kritis", "Critical"], ["Pajak", "Tax"], ["Layanan", "Service"],
  ["Pengeluaran", "Expense"], ["Perangkat", "Device"], ["Notifikasi", "Notifications"],
  ["Kontak, syarat bayar, dan riwayat", "Contacts, payment terms, and history"],
  ["PO dan status persetujuan", "Purchase orders and approval status"],
  ["Barang datang dan stok masuk", "Received goods and incoming stock"],
  ["Invoice dan jatuh tempo", "Invoices and due dates"],
  ["Barang dikembalikan ke pemasok", "Goods returned to suppliers"],
  ["Saldo dan pembayaran pemasok", "Supplier balances and payments"],
  ["Tagihan dan penerimaan pelanggan", "Customer invoices and receipts"],
  ["Beban operasional dan bukti", "Operating expenses and evidence"],
  ["Setelah disetujui, perubahan dicatat sebagai koreksi baru agar riwayat tetap lengkap", "After approval, changes are recorded as a new correction so the history remains complete"],
  ["Buka, soft close, dan hard close", "Open, soft close, and hard close"],
  ["Nilai perolehan dan penyusutan", "Acquisition value and depreciation"],
  ["Kode dan konfigurasi per usaha", "Codes and per-business configuration"],
  ["Hitung fisik dan rekonsiliasi", "Physical count and reconciliation"],
  ["Perpindahan antargudang/cabang", "Transfers between warehouses/branches"],
  ["Harga retail, grosir, dan bertingkat", "Retail, wholesale, and tiered pricing"],
  ["Paket produk dan harga gabungan", "Product packages and bundle pricing"],
  ["Bahan dan takaran F&B", "F&B ingredients and quantities"],
  ["Tambahan dan pilihan menu", "Menu add-ons and options"],
  ["Kapasitas dan status meja", "Table capacity and status"],
  ["Antrean dan status penyajian", "Queue and serving status"],
  ["Durasi, staf, dan harga jasa", "Duration, staff, and service pricing"],
  ["Pelanggan, waktu, dan status", "Customer, time, and status"],
  ["RFM, cohort, dan kelompok", "RFM, cohorts, and groups"],
  ["Poin, penyesuaian, dan persetujuan", "Points, adjustments, and approvals"],
  ["Peran dan permission per cabang", "Roles and permissions per branch"],
  ["Registrasi dan pencabutan perangkat", "Device registration and revocation"],
  ["Printer, scanner, laci, timbangan", "Printer, scanner, cash drawer, and scale"],
  ["Peringatan operasional dan status", "Operational alerts and status"],
  ["Pending, tersedia, reserve, dan penarikan manual", "Pending, available, reserve, and manual withdrawals"],
  ["Pembayaran QRIS platform dan pencairan manual", "Platform QRIS payments and manual settlement"],
  ["Sementara diproses manual setelah persetujuan admin", "Temporarily processed manually after admin approval"],
  ["Status paid hanya dapat diberikan admin dengan referensi transfer", "Only an admin can mark a withdrawal paid with a transfer reference"],
  ["Nomor rekening dienkripsi oleh backend", "The bank account number is encrypted by the backend"],
  ["aplikasi hanya menampilkan empat digit terakhir", "the app only shows the last four digits"],
  ["Minimum Rp50.000", "Minimum Rp50,000"],
  ["Admin memproses transfer manual", "An admin processes the transfer manually"],
  ["tidak ada payout otomatis sebelum KYC/provider disiapkan", "automatic payout remains disabled until KYC and a provider are ready"],
  ["Undangan Auth, role, cabang, dan pencabutan sesi", "Auth invitations, roles, branches, and session revocation"],
  ["Peran berbeda, data yang sama", "Different roles, shared business data"],
  ["Semua cabang, laporan, staf, pembayaran, kebijakan, dan approval", "All branches, reports, staff, payments, policies, and approvals"],
  ["Operasional cabang, stok, shift, refund, dan approval terbatas", "Branch operations, inventory, shifts, refunds, and limited approvals"],
  ["POS, shift sendiri, pelanggan terbatas, dan transaksi yang diizinkan", "POS, own shifts, limited customer access, and permitted transactions"],
  ["Akses awal diberikan ke", "Initial access is granted to"],
  ["Pemilik dapat mencabut akses dan perangkat staf kapan saja", "The owner can revoke staff access and devices at any time"],
  ["PIN 6 digit hanya membuka kembali sesi staf yang sudah terautentikasi pada perangkat tepercaya", "A 6-digit PIN only unlocks an authenticated staff session on a trusted device"],
  ["PIN tidak membuat akun baru dan tidak menggantikan login server", "The PIN does not create an account or replace server sign-in"],
  ["PIN 6 digit hanya membuka kembali sesi akun aktif pada perangkat ini", "A 6-digit PIN only unlocks the active account session on this device"],
  ["Login server tetap diperlukan saat berganti akun staf", "Server sign-in is still required when switching staff accounts"],
  ["Cetak ulang, PDF, dan QR verifikasi per transaksi", "Reprint, PDF, and a verification QR for every transaction"],
  ["Struk tunai dan QRIS yang selesai akan muncul di sini", "Completed cash and QRIS receipts will appear here"],
  ["Pindai QR menggunakan aplikasi pembayaran pelanggan", "Scan the QR with the customer's payment app"],
  ["Keranjang tetap tersimpan sampai Midtrans mengonfirmasi settlement", "The cart remains intact until Midtrans confirms settlement"],
];

export function translateUi(value: string): string {
  if (!value) return value;
  if (i18n.language !== "en") return englishToId[value.toLowerCase()] ?? domainToId[value.toLowerCase()] ?? value;
  if (exact[value]) return exact[value];
  let translated = value;
  for (const [source, target] of phrases) translated = translated.split(source).join(target);
  return translated;
}

function localizeNode(node: React.ReactNode): React.ReactNode {
  if (typeof node === "string") return translateUi(node);
  if (Array.isArray(node)) return node.map(localizeNode);
  return node;
}

export function LocalizedText({ children, style, ...props }: TextProps) {
  const theme=useAppTheme();
  const flat=StyleSheet.flatten(style) as {color?:string}|undefined;
  const color=typeof flat?.color==="string"?flat.color.toUpperCase():"";
  const semantic:Record<string,string>={
    "#111B34":theme.colors.ink,"#0D1B36":theme.colors.navy,"#101B35":theme.colors.ink,
    "#647189":theme.colors.muted,"#66738A":theme.colors.muted,"#526078":theme.colors.muted,
    "#AAB4C2":theme.colors.muted,"#94A0B1":theme.colors.muted,
  };
  return <NativeText {...props} style={[style,theme.resolvedMode==="dark"&&semantic[color]?{color:semantic[color]}:null]}>{localizeNode(children)}</NativeText>;
}

export function localizedAlert(title: string, message?: string, buttons?: AlertButton[]) {
  Alert.alert(
    translateUi(title),
    message ? translateUi(message) : undefined,
    buttons?.map((button) => ({ ...button, text: button.text ? translateUi(button.text) : button.text })),
  );
}
